/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as OpticalTrackerRouteImport } from './routes/optical-tracker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLiveCollectionsRouteImport } from './routes/api/live/collections'
import { Route as ApiExportsCollectionsRouteImport } from './routes/api/exports/collections'
import { Route as ApiEmrImportRouteImport } from './routes/api/emr/import'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const OpticalTrackerRoute = OpticalTrackerRouteImport.update({
  id: '/optical-tracker',
  path: '/optical-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveCollectionsRoute = ApiLiveCollectionsRouteImport.update({
  id: '/api/live/collections',
  path: '/api/live/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportsCollectionsRoute = ApiExportsCollectionsRouteImport.update({
  id: '/api/exports/collections',
  path: '/api/exports/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmrImportRoute = ApiEmrImportRouteImport.update({
  id: '/api/emr/import',
  path: '/api/emr/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/login': typeof LoginRoute
  '/optical-tracker': typeof OpticalTrackerRoute
  '/patients': typeof PatientsRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/emr/import': typeof ApiEmrImportRoute
  '/api/exports/collections': typeof ApiExportsCollectionsRoute
  '/api/live/collections': typeof ApiLiveCollectionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/login': typeof LoginRoute
  '/optical-tracker': typeof OpticalTrackerRoute
  '/patients': typeof PatientsRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/emr/import': typeof ApiEmrImportRoute
  '/api/exports/collections': typeof ApiExportsCollectionsRoute
  '/api/live/collections': typeof ApiLiveCollectionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/login': typeof LoginRoute
  '/optical-tracker': typeof OpticalTrackerRoute
  '/patients': typeof PatientsRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/emr/import': typeof ApiEmrImportRoute
  '/api/exports/collections': typeof ApiExportsCollectionsRoute
  '/api/live/collections': typeof ApiLiveCollectionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/login'
    | '/optical-tracker'
    | '/patients'
    | '/reports'
    | '/revenue'
    | '/api/auth/$'
    | '/api/emr/import'
    | '/api/exports/collections'
    | '/api/live/collections'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/login'
    | '/optical-tracker'
    | '/patients'
    | '/reports'
    | '/revenue'
    | '/api/auth/$'
    | '/api/emr/import'
    | '/api/exports/collections'
    | '/api/live/collections'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/login'
    | '/optical-tracker'
    | '/patients'
    | '/reports'
    | '/revenue'
    | '/api/auth/$'
    | '/api/emr/import'
    | '/api/exports/collections'
    | '/api/live/collections'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRoute
  LoginRoute: typeof LoginRoute
  OpticalTrackerRoute: typeof OpticalTrackerRoute
  PatientsRoute: typeof PatientsRoute
  ReportsRoute: typeof ReportsRoute
  RevenueRoute: typeof RevenueRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEmrImportRoute: typeof ApiEmrImportRoute
  ApiExportsCollectionsRoute: typeof ApiExportsCollectionsRoute
  ApiLiveCollectionsRoute: typeof ApiLiveCollectionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optical-tracker': {
      id: '/optical-tracker'
      path: '/optical-tracker'
      fullPath: '/optical-tracker'
      preLoaderRoute: typeof OpticalTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/collections': {
      id: '/api/live/collections'
      path: '/api/live/collections'
      fullPath: '/api/live/collections'
      preLoaderRoute: typeof ApiLiveCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exports/collections': {
      id: '/api/exports/collections'
      path: '/api/exports/collections'
      fullPath: '/api/exports/collections'
      preLoaderRoute: typeof ApiExportsCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/emr/import': {
      id: '/api/emr/import'
      path: '/api/emr/import'
      fullPath: '/api/emr/import'
      preLoaderRoute: typeof ApiEmrImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRoute,
  LoginRoute: LoginRoute,
  OpticalTrackerRoute: OpticalTrackerRoute,
  PatientsRoute: PatientsRoute,
  ReportsRoute: ReportsRoute,
  RevenueRoute: RevenueRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEmrImportRoute: ApiEmrImportRoute,
  ApiExportsCollectionsRoute: ApiExportsCollectionsRoute,
  ApiLiveCollectionsRoute: ApiLiveCollectionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
