apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eyeflow-web
  namespace: eyeflow
spec:
  ingressClassName: traefik
  rules:
    - host: eyeflow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eyeflow-web
                port:
                  name: http
